POST http://localhost:3000/api/agregados
Content-Type: application/json

{
  "nome": "agreg",
  "projeto_id": 1,
  "descricao": "teste",
  "regras": [
    [
      {
        "key": "nome",
        "operation": "==",
        "value": "Ciclano"
      }
    ]
  ]
}

###

GET http://localhost:3000/api/agregados/estrategia/2

###

GET http://localhost:3000/api/agregados/projeto/1

###

PATCH http://localhost:3000/api/agregados/1
Content-Type: application/json

{
  "nome": "updated",
  "regras": [
    [
      {
        "key": "nome",
        "operation": "==",
        "value": "Fulano"
      },
      {
        "key": "estado",
        "operation": "==",
        "value": "rj"
      }
    ],
    [
      {
        "key": "nome",
        "operation": "==",
        "value": "Admin"
      }
    ]
  ]
}