POST http://localhost:3000/api/agregados
Content-Type: application/json

{
  "nome": "agreg",
  "estrategia_id": 1,
  "descricao": "teste",
  "regras": [
    [
      {
        "key": "nome",
        "operation": "==",
        "value": "Ciclano"
      }
    ]
  ]
}

###

GET http://localhost:3000/api/agregados/estrategia/2

###

GET http://localhost:3000/api/agregados/projeto/1