version: "3"
services:
  database:
    image: mysql
    command: --default-authentication-plugin=caching_sha2_password
    restart: always
    volumes: 
      - ./data:/data/database
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: prtoggles
    networks:
      - webnet
    ports:
      - '3306:3306'
  api:
    container_name: pr-toggles-backend-container
    image: node:16
    build:
      context: .
      target: development
    working_dir: /usr/src/app
    restart: always
    command: bash -c "npm install &&  npx prisma generate && npm run build && npm run start:dev"
    volumes:
      - .:/usr/src/app
    env_file:
    - .env
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    links:
      - database
    networks:
      - webnet
    depends_on:
      - database
networks:
  webnet: