### GET ALL
GET http://localhost:3000/funcionalidades/1

### GET ALL BY PROJETO
GET http://localhost:3000/api/funcionalidades/projeto/4

### CREATE
POST http://localhost:3000/api/funcionalidades
content-type: application/json

{
    "nome": "cor entre azul, verde e vermelho",
    "descricao": "testing",
    "projeto_id": 1,
    "valor": "blue",
    "variacoes": [
      {
        "valor": "green",
        "peso": 25
      },
      {
        "valor": "red",
        "peso": 25
      }
    ]
}

### UPDATE
PATCH http://localhost:3000/funcionalidades/2
content-type: application/json

{
    "ativada": false
}

### DELETE
DELETE http://localhost:3000/funcionalidades/1
