GET http://localhost:3000/clientes

###

GET http://localhost:3000/clientes/1

###

POST http://localhost:3000/clientes
content-type: application/json

{
    "nome_cliente": "pedro lan house",
    "nome_usuario": "Fulano da Silva",
    "email": "fulano@gmail.com",
    "senha": "123",
    "confirmacao_senha": "123"
}

###

PATCH http://localhost:3000/clientes/1
content-type: application/json

{
    "nome": "beltrano updated"
}

###

DELETE http://localhost:3000/clientes/1