POST http://localhost:3000/api/estrategias/
Content-Type: application/json

{
  "funcionalidade_id": 1,
  "ambiente": "dev",
  "valor": "teste valor"
}


###

GET http://localhost:3000/api/estrategias/

###

GET http://localhost:3000/estrategias/funcionalidade/5/ambiente/prod


###

GET http://localhost:3000/api/estrategias/1/agregados


###

PATCH http://localhost:3000/api/estrategias/hasAgregado
Content-Type: application/json

{
  "agregado_id": 3,
  "estrategia_id": 13,
  "valor": "true",
  "ativado": true
}

###

PATCH http://localhost:3000/api/estrategias/1
Content-Type: application/json

{
  "valor": "fodase",
  "variacoes": [
    {
      "valor": "teste valor",
      "peso": 50
    }
  ]
}