GET http://localhost:3000/projetos

###

GET http://localhost:3000/api/projetos/

###

GET http://localhost:3000/api/projetos/cliente/1

###

POST http://localhost:3000/api/projetos
content-type: application/json

{
    "nome": "Consultoria",
    "descricao": "blablasadadsads",
    "cliente_id": 1
}

###

PATCH http://localhost:3000/projetos/1
content-type: application/json

{
    "descricao": "att descricao"
}

###
DELETE http://localhost:3000/projetos/1


###

POST http://localhost:3000/api/projetos/funcionalidades
content-type: application/json

{
  "chave_ambiente": "381dfd7e-8857-422a-b30c-4e45b0b48f95",
  "contexto": {
    "idade": 19,
    "user_id": "123"
  }
}