GET http://localhost:3000/auth/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZ21haWwuY29tIiwic3ViIjo0LCJuYW1lIjoidGVzdCBoYXNoIiwiY2xpZW50ZV9pZCI6MiwiaWF0IjoxNjY0MjQ5ODk0fQ.JjLIGjauV9Olrnm3ubJM0CcCt2QO65oo8x-SbvFpMkg

###

POST http://localhost:3000/auth/login
content-type: application/json

{
    "username": "ciclano@gmail.com",
    "password": "123"
}